// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY4opdJRg5QS0V_kRHfWSSq552niSYyQY',
    appId: '1:160609205998:web:5f7ba102c55c11cef27dff',
    messagingSenderId: '160609205998',
    projectId: 'womensafety-ea0ae',
    authDomain: 'womensafety-ea0ae.firebaseapp.com',
    storageBucket: 'womensafety-ea0ae.firebasestorage.app',
    measurementId: 'G-7RDR21MMXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwPETtSeXB9KQNvS-gE1uu0m_dKJbawAo',
    appId: '1:160609205998:android:f249b264164b5706f27dff',
    messagingSenderId: '160609205998',
    projectId: 'womensafety-ea0ae',
    storageBucket: 'womensafety-ea0ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4HUhr598gE5j9rkpUyT1I8eWMpF1HTkg',
    appId: '1:160609205998:ios:a36245f08df8c212f27dff',
    messagingSenderId: '160609205998',
    projectId: 'womensafety-ea0ae',
    storageBucket: 'womensafety-ea0ae.firebasestorage.app',
    iosBundleId: 'com.example.womenhelpdesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4HUhr598gE5j9rkpUyT1I8eWMpF1HTkg',
    appId: '1:160609205998:ios:a36245f08df8c212f27dff',
    messagingSenderId: '160609205998',
    projectId: 'womensafety-ea0ae',
    storageBucket: 'womensafety-ea0ae.firebasestorage.app',
    iosBundleId: 'com.example.womenhelpdesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY4opdJRg5QS0V_kRHfWSSq552niSYyQY',
    appId: '1:160609205998:web:4bedf5255337b5b2f27dff',
    messagingSenderId: '160609205998',
    projectId: 'womensafety-ea0ae',
    authDomain: 'womensafety-ea0ae.firebaseapp.com',
    storageBucket: 'womensafety-ea0ae.firebasestorage.app',
    measurementId: 'G-7G589BGST6',
  );
}
